### ISSUE TITLE
Decide if we need both ldaptor.testutil and  ldaptor.test.util

### ISSUE THREAD

**Issue by adiroiban** [twisted/ldaptor#91]
I guess that ldaptor.testutil should be moved to ldaptor.test.util so that we have it only in test and not used it outside of ldaptor.

While working on this check if we can get 100% coverage for ldaptor.test.util and enable codecov.io reporting for whole tests 

in codecov.yml now we have
```
      tests:
        target: 100%
        paths:
          - "ldaptor/test/test_*"
```

It would be nice to have 
```
      tests:
        target: 100%
        paths:
          - "ldaptor/test/*"
```
